### ISSUE TITLE
CUDA out of memory on RTX4090

### ISSUE THREAD

**Issue by jong3** [aqlaboratory/openfold#511]
I encountered a `RuntimeError: CUDA out of memory` while training openfold on my custom MSA dataset. Here's the exact error message:
![{459E0DBB-7CDF-46A8-9607-CFF2DB1966E1}](https://github.com/user-attachments/assets/d2211c9c-63f7-4623-9158-7284c46ed547)

**My Modifications:**
Adjusted evoformer_stack.no_blocks to 4.
Adjusted structure_module.no_blocks to 2.

**Model Parameters and Memory Usage:**
![{23C30FC5-5DEF-4399-9566-FBBD93A36A65}](https://github.com/user-attachments/assets/078a7d5c-0aec-4976-ad35-811880fe3afc)

**Environment and Configuration:**
GPU: RTX 4090 (23GB VRAM)
CUDA version: 11.8
PyTorch version: 1.12.1

Thanks

**Comment by jong3** [comment]
I have solved this problem with the following changes:

{
"multimer_config_update.data.train.crop_size": 384,
}

This value defaults to 640 in multimer's train. But for my mission, 256 is good enough.
